### ISSUE TITLE
fejléc maradjon listáknál

### ISSUE THREAD

**Issue by dombiarpi** [dombiarpi/konyvtar-palma#15]

**Comment by dombiarpi** [comment]
Ez nem lesz megoldva. A stickyHeader="true" hibásan működik primefaces táblánál ha filterek is vannak. Workaround-okra nincs idő se, kedv se.

**Comment by palmagerendai** [comment]
Sírok...

**Comment by dombiarpi** [comment]
Hátha meg tudlak győzni, hogy erre nincs is igazából szükséged. :)
