### ISSUE TITLE
jogosultság-kezelés

### ISSUE THREAD

**Issue by dombiarpi** [dombiarpi/konyvtar-palma#24]

**Comment by palmagerendai** [comment]
Mire lesz jogosultságom?

**Comment by dombiarpi** [comment]
Neked mindenre. Azoknak lesz korlátozott jogosultsága, akik nem könyvtárosok, de mondjuk meg tudják nézni, hogy kivehető-e egy könyv stb, de nem tudnak kölcsönözni, visszatenni önállóan
